formData --->
{
    "_id": {
      "$oid": "680a4eb70455cf40307c7345"
    },
    "module_id": 2,
    "sub_module_id": 7,
    "platform": "web",
    "form_data": [
      {
        "id": 1,
        "label": "Created At",
        "name": "created_at",
        "placeholder": "Created At",
        "type": "DATE_RANGE",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": true,
        "validation_error": "This field is required",
        "is_show": false,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 1,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 1,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 2,
        "label": "Created Name",
        "name": "created_name",
        "placeholder": "Created Name",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": true,
        "validation_error": "This field is required",
        "is_show": false,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 2,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 2,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 3,
        "label": "Account Type",
        "name": "login_type_id",
        "actual_name": "login_type_name",
        "placeholder": "Account Type",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": true,
        "child_dependency": [
          {
            "visibilty": "Direct",
            "parent_field_value": "System User",
            "child_field_name": "user_role_id",
            "child_field_option": []
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "Warehouse",
            "child_field_name": "user_role_id",
            "child_field_option": []
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "Service Vendor",
            "child_field_name": "user_role_id",
            "child_field_option": []
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "System User",
            "child_field_name": "data_rights",
            "child_field_option": []
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "Warehouse",
            "child_field_name": "data_rights",
            "child_field_option": []
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "Service Vendor",
            "child_field_name": "data_rights",
            "child_field_option": []
          }
        ],
        "options": [],
        "data_type": "string",
        "sequence": 3,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 3,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true,
        "api_path": "rbac/read-login-types",
        "api_payload": [
          3,
          4,
          9,
          11,
          12
        ],
        "api_payload_key": "login_type_ids"
      },
      {
        "id": 3,
        "label": "Role",
        "name": "user_role_id",
        "actual_name": "user_role_name",
        "placeholder": "Role",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": true,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 3,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 3,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true,
        "api_path": "dropdown/read-dropdown"
      },
      {
        "id": 3,
        "label": "Data Rights",
        "name": "data_rights",
        "placeholder": "Data Rights",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [
          {
            "visibilty": "Direct",
            "parent_field_value": "Team Wise",
            "child_field_name": "data_right_values",
            "child_field_option": [],
            "api_path": "user/read-dropdown"
          },
          {
            "visibilty": "Direct",
            "parent_field_value": "State Wise",
            "child_field_name": "data_right_values",
            "child_field_option": [],
            "api_path": "postal-code/states"
          }
        ],
        "options": [
          {
            "label": "Team Wise",
            "value": "Team Wise"
          },
          {
            "label": "State Wise",
            "value": "State Wise"
          }
        ],
        "data_type": "string",
        "sequence": 3,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 3,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true
      },
      {
        "id": 3,
        "label": "Data Right Values",
        "name": "data_right_values",
        "placeholder": "Data Right Values",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 3,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 3,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true
      },
      {
        "id": 3,
        "label": "Name",
        "name": "name",
        "placeholder": "Name",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 3,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 3,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true
      },
      {
        "id": 4,
        "label": "Mobile",
        "name": "mobile",
        "placeholder": "Mobile",
        "type": "SHORT_TEXT",
        "min_length": 10,
        "max_length": 10,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 4,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 4,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 5,
        "label": "Email",
        "name": "email",
        "placeholder": "Email",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "show_guide": false,
        "required": false,
        "read_only": false,
        "validation_error": "",
        "parent_id": 1,
        "child_dependency": [],
        "is_show": true,
        "is_enable": true,
        "is_parent_dependency": true,
        "is_child_dependency": false,
        "options": [],
        "data_type": "string",
        "sequence": 5,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "icon": "",
        "grid_column": 1,
        "validation_pattern": null,
        "listing_sequence": 5
      },
      {
        "id": 6,
        "label": "Employee Code",
        "name": "user_code",
        "placeholder": "Employee Code",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 6,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 6,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "is_duplicate": true
      },
      {
        "id": 7,
        "label": "Designation",
        "name": "designation",
        "placeholder": "Designation",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 7,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 7,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true,
        "api_path": "dropdown/read-dropdown"
      },
      {
        "id": 8,
        "label": "Weekly Off",
        "name": "weekly_off",
        "placeholder": "Weekly Off",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [
          {
            "label": "Sunday",
            "value": "Sunday"
          },
          {
            "label": "Monday",
            "value": "Monday"
          },
          {
            "label": "Tuesday",
            "value": "Tuesday"
          },
          {
            "label": "Wednesday",
            "value": "Wednesday"
          },
          {
            "label": "Thrusday",
            "value": "Thrusday"
          },
          {
            "label": "Friday",
            "value": "Saturday"
          },
          {
            "label": "Saturday",
            "value": "Saturday"
          }
        ],
        "data_type": "string",
        "sequence": 8,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 8,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 9,
        "label": "Reporting Manager",
        "name": "reporting_manager_id",
        "actual_name": "reporting_manager_name",
        "placeholder": "Reporting Manager",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 9,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 9,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 10,
        "label": "Pincode",
        "name": "pincode",
        "placeholder": "Pincode",
        "type": "SHORT_TEXT",
        "min_length": 6,
        "max_length": 6,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 10,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 10,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 11,
        "label": "State",
        "name": "state",
        "placeholder": "State",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "number",
        "sequence": 11,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": false,
        "listing_sequence": 11,
        "filter_checked": false,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": false,
        "key_name": "",
        "api_path": "postal-code/states"
      },
      {
        "id": 12,
        "label": "District",
        "name": "district",
        "placeholder": "District",
        "type": "SINGLE_SELECT",
        "min_length": 0,
        "max_length": 0,
        "required": true,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "options": [],
        "data_type": "number",
        "sequence": 12,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": false,
        "listing_sequence": 12,
        "filter_checked": false,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": false,
        "key_name": "",
        "api_path": "postal-code/states"
      },
      {
        "id": 13,
        "label": "Address",
        "name": "address",
        "placeholder": "Address",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 13,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 13,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 14,
        "label": "City",
        "name": "city",
        "placeholder": "City",
        "type": "SHORT_TEXT",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": false,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "child_dependency": [],
        "data_type": "string",
        "sequence": 14,
        "class_name": "xxl:col-span-3 xl:col-span-4 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 14,
        "filter_checked": true,
        "is_change": false,
        "key_source": "default",
        "pattern": "",
        "is_header_config": true
      },
      {
        "id": 15,
        "label": "Profile Pic",
        "name": "profile_pic",
        "placeholder": "Profile Pic",
        "type": "UPLOAD",
        "min_length": 0,
        "max_length": 0,
        "required": false,
        "read_only": true,
        "validation_error": "This field is required",
        "is_show": true,
        "is_parent_dependency": false,
        "is_child_dependency": false,
        "is_header_config": true,
        "child_dependency": [],
        "options": [],
        "data_type": "string",
        "sequence": 16,
        "class_name": "xxl:col-span-6 xl:col-span-9 col-span-12",
        "list_view_checked": true,
        "listing_sequence": 15,
        "filter_checked": false,
        "is_duplicate": true,
        "api_path": "",
        "is_change": false,
        "key_source": "default",
        "pattern": ""
      }
    ],
    "form_type": "add",
    "created_id": 1,
    "created_name": "Developer",
    "is_delete": 0,
    "org_id": 0,
    "created_unix_time": 1738778614,
    "status": 1,
    "created_at": {
      "$date": "2025-02-05T18:03:37.275Z"
    },
    "updated_at": {
      "$date": "2025-02-05T18:03:37.275Z"
    },
    "__v": 0,
    "form_id": 4,
    "form_source": "default",
    "updated_name": "Developer"
  }